uk.ac.gda.devices.bssc: include scripts in binary build
Otherwise uk.ac.gda.devices.bssc/scripts does not exist in the server build,
resulting in this exception during server startup:

  gda.jython.GDAJythonInterpreter - Unable to locate plugin for script location uk.ac.gda.devices.bssc/scripts, these scripts will not be accessible
  java.io.IOException: Script folder /scratch/gda/master-mx/servers/server_20170817-1154_linux64/plugins/../utilities/uk.ac.gda.devices.bssc/scripts does not exist
      at gda.jython.GDAJythonInterpreter.configure(GDAJythonInterpreter.java:231)
      at gda.jython.JythonServer.configure(JythonServer.java:343)
      at gda.util.SpringObjectServer.configureAllConfigurablesInApplicationContext(SpringObjectServer.java:315)
      at gda.util.SpringObjectServer.startServer(SpringObjectServer.java:273)
      at gda.util.ObjectServer.configure(ObjectServer.java:243)
      at gda.util.ObjectServer.createServerImpl(ObjectServer.java:131)
      at gda.util.ObjectServer.spawn(ObjectServer.java:440)
      at uk.ac.diamond.daq.server.configuration.commands.ObjectServerCommand.execute(ObjectServerCommand.java:44)
      at uk.ac.diamond.daq.server.GDAServerApplication.start(GDAServerApplication.java:74)
      at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
      at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
      at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
      at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
      at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
      at org.eclipse.equinox.launcher.Main.main(Main.java:1488)